version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file: "compose.env"
    depends_on:
      - post
  post:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres