name: Build Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build fat jar
        run: ./gradlew check web:shadowJar

      - name: Build Docker image
        run: |
          docker build -t vtornik-web .
          docker tag vtornik-web msmych/vtornik-web:latest

      - name: Push image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push msmych/vtornik-web:latest

      - name: Deploy to host
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "${{ secrets.SSH_PASSWORD }}" | sudo -S echo "Connected to server"
            sudo openssl pkcs12 -export \
              -in /etc/letsencrypt/live/matvey.uk/fullchain.pem \
              -inkey /etc/letsencrypt/live/matvey.uk/privkey.pem \
              -out /etc/letsencrypt/live/matvey.uk/keystore.p12 \
              -name matvey-p12 \
              -CAfile /etc/letsencrypt/live/matvey.uk/chain.pem \
              -caname "matvey-letsencrypt" \
              -passout "pass:${{ secrets.JKS_PASS }}"
            sudo chmod 644 /etc/letsencrypt/live/matvey.uk/keystore.p12
            sudo keytool -importkeystore \
              -deststorepass "${{ secrets.JKS_PASS }}" \
              -destkeypass "${{ secrets.JKS_PASS }}" \
              -destkeystore /etc/letsencrypt/live/matvey.uk/keystore.jks \
              -srckeystore /etc/letsencrypt/live/matvey.uk/keystore.p12 \
              -srcstoretype PKCS12 \
              -srcstorepass "${{ secrets.JKS_PASS }}" \
              -alias matvey-p12 \
              -noprompt
            sudo chmod 644 /etc/letsencrypt/live/matvey.uk/keystore.jks
            mkdir ~/vtornik || true
            cd ~/vtornik
            cat > docker-compose.yaml << EOL
            services:
              web:
                image: msmych/vtornik-web:latest
                ports:
                  - "8443:8443"
                volumes:
                  - /etc/letsencrypt/live/matvey.uk:/certs
                environment:
                  PROFILE: PROD
                  APP_SECRET: \${DEV_APP_SECRET}
                  DB_URL: \${DEV_DB_URL}
                  DB_USERNAME: \${DEV_DB_USERNAME}
                  DB_PASSWORD: \${DEV_DB_PASSWORD}
                  GITHUB_CLIENT_ID: \${DEV_GITHUB_CLIENT_ID}
                  GITHUB_CLIENT_SECRET: \${DEV_GITHUB_CLIENT_SECRET}
                  TMDB_API_KEY: \${DEV_TMDB_API_KEY}
            EOL
            cat docker-compose.yaml
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            DEV_APP_SECRET="${{ secrets.DEV_APP_SECRET }}" \
              DEV_DB_URL="${{ secrets.DEV_DB_URL }}" \
              DEV_DB_USERNAME="${{ secrets.DEV_DB_USERNAME }}" \
              DEV_DB_PASSWORD="${{ secrets.DEV_DB_PASSWORD }}" \
              DEV_GITHUB_CLIENT_ID="${{ secrets.DEV_GITHUB_CLIENT_ID }}" \
              DEV_GITHUB_CLIENT_SECRET="${{ secrets.DEV_GITHUB_CLIENT_SECRET }}" \
              DEV_TMDB_API_KEY="${{ secrets.DEV_TMDB_API_KEY }}" \
              docker compose up -d 
